apps/accounts/urls.py
"""
Основная точка входа в приложение accounts
"""
from django.contrib.auth.views import LoginView
from django.urls import path, reverse_lazy

from .views import AboutMeView, RegisterView, MyLogoutView

app_name = "accounts"

urlpatterns = [
    path("profile/", AboutMeView.as_view(), name="about-me"),
    path("registration/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(
            template_name="accounts/login.html",
            redirect_authenticated_user=True,
            next_page=reverse_lazy("accounts:about-me"),
        ),
        name="login",
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
]

apps/chat/urls.py
"""
Основная точка входа в приложение, содержит роуты приложения Chat
"""
from django.urls import path

from .views import Index, Room

app_name = "chat"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("<str:room_name>/", Room.as_view(), name="room"),
]

config/urls.py
"""
Основная точка входа в проект chat_cube, содержит стартовые urls
"""
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("apps.chat.urls")),
    path("accounts/", include("apps.accounts.urls")),

    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    class Meta:
        db_table = "auth_user"


class Profile(models.Model):
    """Модель профиля пользователя"""

    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
    )

    nick_name = models.CharField(max_length=40)

apps/accounts/forms.py
"""
Формы для приложения accounts
"""

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm,
)

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    """
    Форма для создания CustomUser
    """

    class Meta:
        model = User
        fields = ("username",)

apps/chat/forms.py
"""
Формы для приложения chat
"""
from django import forms


class IndexForm(forms.Form):
    """
    Форма для создания комнаты и задания ника для пользователя
    """

    room_name = forms.CharField(max_length=40)
    nick_name = forms.CharField(max_length=40)

apps/accounts/views.py
"""
Файл представлений для приложения Accounts
"""
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    CreateView,
)

from .forms import CustomUserCreationForm
from .models import Profile


class AboutMeView(TemplateView):
    """
    Представление для отображения информации о пользователе
    """

    template_name = "accounts/about-me.html"


class MyLogoutView(LogoutView):
    """
    Представление для обработки выхода пользователя из системы.
    """

    next_page = reverse_lazy("accounts:login")


class RegisterView(CreateView):
    """
    РПредставление для регистрации пользователя
    """

    form_class = CustomUserCreationForm
    template_name = "accounts/registration.html"
    success_url = reverse_lazy("accounts:about-me")

    def form_valid(self, form) -> HttpResponse:
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        Profile.objects.create(user=self.object)
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response

apps/chat/views.py
"""
Файл представлений для приложения chat
"""
import logging

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from .forms import IndexForm

logger = logging.getLogger(__name__)


class Index(View):
    """
    Просмотр страницы индекса.

    Это представление обрабатывает запросы GET и POST для страницы индекса.
    """

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, "accounts/registration.html")
        nick_name = request.user.profile.nick_name
        return render(request, "chat/index.html", {"nick_name": nick_name})

    def post(self, request):
        index_form = IndexForm(request.POST)
        if index_form.is_valid():
            nick_name = index_form.cleaned_data["nick_name"]
            room_name = index_form.cleaned_data["room_name"]
            current_user = request.user
            current_user.profile.nick_name = nick_name
            current_user.profile.save()
            return render(
                request,
                "chat/room.html",
                {
                    "room_name": room_name,
                },
            )
        return render(
            request,
            "chat/index.html",
        )


class Room(View):
    """
     Просмотр страницы комнаты.

    Это представление обрабатывает запросы GET и POST для страницы комнаты.
    """

    def get(self, request, room_name):
        logger.info(f"Room_get with {room_name} ")
        return render(
            request,
            "chat/room.html",
            {
                "room_name": room_name,
            },
        )

    def post(self, request, room_name):
        message = request.POST.get("message", None)
        if message:
            channel_layer = get_channel_layer()
            async_to_sync(channel_layer.group_send)(
                f"chat_{room_name}", {"type": "chat.message", "message": message}
            )
            return HttpResponse("Message sent")
        return HttpResponse("Message not sent")

templates/accounts/about-me.html
{% extends 'accounts/base.html' %}

{% block title %}
About me
{% endblock %}


{% block body %}
<h1>Пользователь #{{user.profile.pk}}</h1>
{% if user.is_authenticated %}

<h2>Подробно</h2>
<div>
    <p>Имя: {{ user.username }}</p>
    <p>Ник: {{user.profile.nick_name}}</p>

    <a href="{% url 'chat:index' %}">Перейти в чат</a>

    {% else %}
    <h2>User is anonymous</h2>
    {% endif %}
</div>


{% endblock %}

templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}

  {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>
</form>


{% endblock %}

templates/accounts/registration.html
{% extends 'accounts/base.html' %}

{% block title %}
  Registrate
{% endblock %}

{% block body %}

<h1>Registration</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register">
</form>

{% endblock %}

templates/chat/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    <div>
        ID комнаты?
        <input id="room_name" name="room_name" size="50">
    </div>
    <div>

        Ваш ник:
        <input id="nick_name" name="nick_name" value="{{ nick_name }}" size="50">
        <br>
        <button id="submit_button" type="submit">Вход</button>
    </div>
    <script>
            document.querySelector('#nick_name').focus();
            document.querySelector('#nick_name').onkeyup = function(e) {
                if (e.key === 'Enter') {  // enter, return
                    document.querySelector('#submit_button').click();
                }
            };
    </script>
</form>
</body>
</html>

templates/chat/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room-name" }}

<script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };

</script>
</body>
</html>